var apple_phones = [
    { "name": "iPhone 12 Pro Max", "id": "ip12promax" },
    { "name": "iPhone 12 Pro", "id": "ip12pro" },
    { "name": "iPhone 12 Mini", "id": "ip12mini" },
    { "name": "iPhone 12", "id": "ip12" },
    { "name": "iPhone 11 Pro Max", "id": "ip11promax" },
    { "name": "iPhone 11 Pro", "id": "ip11pro" },
    { "name": "iPhone 11", "id": "ip11" },
    { "name": "iPhone XS Max", "id": "ipxsmax" },
    { "name": "iPhone XS", "id": "ipxs" },
    { "name": "iPhone X", "id": "ipx" },
    { "name": "iPhone XR", "id": "ipxr" },
    { "name": "iPhone SE (2020)", "id": "ipse" },
    { "name": "iPhone 8+", "id": "ip8plus" },
    { "name": "iPhone 8", "id": "ip8" },
    { "name": "iPhone 7+", "id": "ip7plus" },
    { "name": "iPhone 7", "id": "ip7" },
    { "name": "iPhone 6+ / 6S+", "id": "ip6plus" },
    { "name": "iPhone 6 / 6s", "id": "ip6" },
    // { "name": "iPhone", "id": "ip" },
];