var samsung_phones = [
    { "name": "Galaxy S10+", "id": "s10plus" },
    { "name": "Galaxy S10", "id": "s10" },
    { "name": "Galaxy S9+", "id": "s9plus" },
    { "name": "Galaxy S9", "id": "s9" },
    { "name": "Galaxy S8+", "id": "s8plus" },
    { "name": "Galaxy S8", "id": "s8" },
    { "name": "Galaxy S7 Edge", "id":"s7edge" },
    { "name": "Galaxy S7", "id": "s7" },
    { "name": "Galaxy S6 Edge", "id": "s6edge" },
    { "name": "Galaxy S6", "id": "s6"},
    { "name": "Galaxy A71", "id": "a71" },
    { "name": "Galaxy A70", "id": "a70" },
    { "name": "Galaxy A51", "id": "a51" },
    { "name": "Galaxy A50", "id": "a50" },
    { "name": "Galaxy A30", "id": "a30" },
    { "name": "Galaxy A20", "id": "a20" },
    { "name": "Galaxy A10", "id": "a10" },
    // { "name": "Galaxy", "id": "" },
];